package com.dy.learn.learn.dao.mapper;

import com.dy.learn.learn.dao.entity.TaskInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TaskInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated
     */
    int insert(TaskInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated
     */
    int insertSelective(TaskInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated
     */
    TaskInfo selectByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TaskInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TaskInfo record);


    List<TaskInfo> getAllTaskList();

    TaskInfo getTaskByNameAndGroup(@Param("jobName") String jobName, @Param("jobGroup") String jobGroup);

}