package com.dy.learn.learn.dao.entity;

import java.math.BigDecimal;
import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_test.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_test.userName
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_test.user_nameSec
     *
     * @mbggenerated
     */
    private String userNamesec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_test.amt
     *
     * @mbggenerated
     */
    private BigDecimal amt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_test.last_login_time
     *
     * @mbggenerated
     */
    private Date lastLoginTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_test.id
     *
     * @return the value of user_info_test.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_test.id
     *
     * @param id the value for user_info_test.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_test.userName
     *
     * @return the value of user_info_test.userName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_test.userName
     *
     * @param username the value for user_info_test.userName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_test.user_nameSec
     *
     * @return the value of user_info_test.user_nameSec
     *
     * @mbggenerated
     */
    public String getUserNamesec() {
        return userNamesec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_test.user_nameSec
     *
     * @param userNamesec the value for user_info_test.user_nameSec
     *
     * @mbggenerated
     */
    public void setUserNamesec(String userNamesec) {
        this.userNamesec = userNamesec == null ? null : userNamesec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_test.amt
     *
     * @return the value of user_info_test.amt
     *
     * @mbggenerated
     */
    public BigDecimal getAmt() {
        return amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_test.amt
     *
     * @param amt the value for user_info_test.amt
     *
     * @mbggenerated
     */
    public void setAmt(BigDecimal amt) {
        this.amt = amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_test.last_login_time
     *
     * @return the value of user_info_test.last_login_time
     *
     * @mbggenerated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_test.last_login_time
     *
     * @param lastLoginTime the value for user_info_test.last_login_time
     *
     * @mbggenerated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }
}